version: '3'

services:

  ##
  ## OrientDB is the main database Convergence uses to store data.
  ##
  orientdb:
    image: ${CONVERGENCE_DOCKER_REPO}/convergence-orientdb:latest
    # restart: always
    environment:
      ORIENTDB_ROOT_PASSWORD: "password"
      ORIENTDB_OPTS_MEMORY: "-Xms384m -Xmx384m"
      JAVA_OPTS: "-Dstorage.wal.allowDirectIO=false"
    volumes:
      - ./data/orientdb/databases:/orientdb/databases
      - ./data/orientdb/backup:/orientdb/backup

  ##
  ## A bootstrapping container that serves as the seed node for the distributed
  ## Convergence cluster.
  ##
  cluster-seed:
    image: ${CONVERGENCE_DOCKER_REPO}/convergence-cluster-seed:${CONVERGENCE_DOCKER_TAG}
    command: "-Dlog4j.configurationFile=/etc/convergence/log4j2.xml"
    # restart: always
    volumes:
       - ./config/convergence/log4j2.xml:/etc/convergence/log4j2.xml
    environment:
      JAVA_OPTS: "-Xmx64m -Xss512k -XX:CICompilerCount=1 -XX:-TieredCompilation"
      REMOTING_EXTERNAL_HOSTNAME: cluster-seed
      CLUSTER_SEED_NODES: cluster-seed

  ##
  ## The main Convergence Server. In this compose file this single node boots all
  ## server roles.
  ##
  server:
    image: ${CONVERGENCE_DOCKER_REPO}/convergence-server:${CONVERGENCE_DOCKER_TAG}
    # restart: always
    volumes:
       - ./config/convergence/log4j2.xml:/opt/convergence-server/conf/log4j2.xml
       - ./config/convergence/convergence-server.conf:/opt/convergence-server/conf/convergence-server.conf
    links:
     - cluster-seed
     - orientdb

  ##
  ## Serves the Convergence Admin Console
  ##
  admin-console:
    image: ${CONVERGENCE_DOCKER_REPO}/convergence-admin-console:${CONVERGENCE_DOCKER_TAG}
    # restart: always
    environment:
      CONVERGENCE_SERVER_REALTIME_API: "https://${DOCKER_HOSTNAME}/realtime/"
      CONVERGENCE_SERVER_REST_API: "https://${DOCKER_HOSTNAME}/rest/"
      CONVERGENCE_CONSOLE_BASE_URL: "/console/"

  ##
  ## The proxy simply creates a single HTTP/HTTP Ingress and forwards traffic
  ## to the appropriate container.
  ##
  proxy:
    image: nginx:1.17.6-alpine
    # restart: always
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/html:/usr/share/nginx/html
      - ./config/nginx/ssl:/etc/nginx/ssl/
    depends_on:
      - orientdb
      - server
      - admin-console
    ports:
      - "443:443"
      - "80:80"
